### ISSUE TITLE
_fetchAll doesn't return an error when it fails

### ISSUE THREAD

**Issue by lucas42** [Financial-Times/cmdb.js#9]
Functions which call _fetch or _fetchCount, throw nice errors when a problem occurs (eg network timeout or 500 error returned by the CMDB).

However, functions which call _fetchAll swallow their errors up and don't return anything.  This makes it harder to show a useful message to the user about what's gone wrong.

**Comment by Limess** [comment]
This is no longer swallowed in the latest versions. The first error which occurred is propagated and the request ends.
